format = """$directory $git_branch $git_status
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[λ](bold blue)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[λ](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "~/"


[git_branch]
symbol = ""

[git_status]


